import { spawn } from "node:child_process";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { PROJECT_ROOT } from "./config.js";
import { sha256Text } from "./hash.js";
type Json=Record<string,any>;
export async function attachBioLM(input:{sequencePath:string;structurePath?:string;proteinId:string;queryTaxonId?:number;excludedAccessions:string[];runDir:string;env:NodeJS.ProcessEnv;bundle?:Json}):Promise<Json>{
 const required=(key:string)=>{const v=input.env[key];if(!v) throw new Error(`BioLM requires host binding ${key}`);return v;};
 const directory=join(input.runDir,"evidence");await mkdir(directory,{recursive:true});const output=join(directory,"biolm.json");
 const args=[join(PROJECT_ROOT,"python","biolm.py"),"predict","--model-root",required("BIOLM_MODEL_ROOT"),"--index",required("BIOLM_INDEX"),"--fasta",input.sequencePath,"--output",output,"--policy",join(PROJECT_ROOT,"config","biolm_policy.json"),"--device",input.env.BIOLM_DEVICE||"cuda:0"];
 if(input.env.BIOLM_ALLOW_SMOKE_INDEX==="1")args.push("--allow-smoke-index");for(const id of input.excludedAccessions)args.push("--exclude-accession",id);
 await new Promise<void>((resolve,reject)=>{const child=spawn(required("BIOLM_PYTHON"),args,{env:input.env,stdio:"inherit"});const timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error("BioLM timed out"));},1800000);child.on("error",e=>{clearTimeout(timer);reject(e)});child.on("close",code=>{clearTimeout(timer);code===0?resolve():reject(new Error(`BioLM failed: ${code}`))})});
 const evidence=JSON.parse(await readFile(output,"utf8"));if(evidence.schema!=="biolm-evidence.v1"||evidence.models.length!==3)throw new Error("Invalid BioLM evidence");
 const textHash=(text:string)=>sha256Text(`${text.replace(/\r\n?/g,"\n").trimEnd()}\n`);
 const bundle:Json=input.bundle??{schema_version:"pi-function-evidence.v3",protein:{protein_id:input.proteinId,sequence_input_sha256:textHash(await readFile(input.sequencePath,"utf8")),structure_input_sha256:input.structurePath?textHash(await readFile(input.structurePath,"utf8")):null,structure_available:Boolean(input.structurePath),query_taxon_id:input.queryTaxonId??null,query_taxon_id_source:input.queryTaxonId===undefined?"unavailable":"cli"},runtime:{search_backends:{sequence:"biolm_only",structure:null}},domain_segments:[],sequence_hits:[],structure_hits:[],uniprot_annotations:[],pdb_annotations:[],negative_search_evidence:[],intrinsic_evidence:{},limitations:[],evidence_ids:[]};
 const existing=bundle.candidate_sources??{};bundle.candidate_sources={...existing,providers:[...(existing.providers??[]),{provider:"BioLM",status:"completed",endpoint_or_path:required("BIOLM_INDEX"),release:"pinned-t0",cache_hit:false}],go_candidates:[...(existing.go_candidates??[]),...evidence.candidates]};
 bundle.biolm_interface={models:evidence.models.map((m:Json)=>m.model),descriptions:evidence.models.map((m:Json)=>String(m.text).split("\n")[0]),limitations:evidence.limitations,smoke_only:evidence.smoke_only};bundle.limitations=[...(bundle.limitations??[]),...(evidence.limitations??[])];bundle.evidence_ids=[...new Set([...(bundle.evidence_ids??[]),...evidence.candidates.map((c:Json)=>c.evidence_id),"biolm:retrieval-completed"])] ;
 await writeFile(join(directory,"biolm_summary.md"),evidence.models.map((m:Json)=>m.text).join("\n\n"));await writeFile(join(directory,"evidence_bundle.json"),JSON.stringify(bundle,null,2));await mkdir(join(input.runDir,"input"),{recursive:true});await copyFile(input.sequencePath,join(input.runDir,"input","sequence.fasta"));if(input.structurePath)await copyFile(input.structurePath,join(input.runDir,"input","structure.pdb"));await writeFile(join(directory,"evidence_summary.md"),evidence.models.map((m:Json)=>m.text).join("\n\n"));await writeFile(join(input.runDir,"evidence_manifest.json"),JSON.stringify({status:"completed",backend:"biolm_only",smoke_only:evidence.smoke_only,outputs:{evidence_bundle:"evidence/evidence_bundle.json",evidence_summary:"evidence/evidence_summary.md"}},null,2));return bundle;
}
